### PR TITLE
Ignore .spec.state of ControlPlaneMachineSet

### PR DESCRIPTION
**Pull request by DebakelOrakel**
## Checklist

- [x] The PR has a meaningful title. It will be used to auto-generate the
      changelog.
      The PR has a meaningful description that sums up the change. It will be
      linked in the changelog.
- [x] PR contains a single logical change (to build a better changelog).
- [ ] Update the documentation.
- [x] Categorize the PR by adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog.
- [ ] Link this PR to related issues or PRs.

### CODE REVIEW

**Comment by simu** [comment]
Why ignore this instead of configuring it properly via hierarchy?

**Comment by DebakelOrakel** [comment]
I tested it and:
```
  openshift4_nodes:
    nodeGroups:
      master:
        replicas: 3
        state: 'Active'
```
does not change a thing, but thats probably due to incompetence on my side 🤦‍♂️

**Comment by DebakelOrakel** [comment]
> As far as I'm aware the field in the resource isn't immutable, so I don't see a real reason to ignore diffs for it.

You are right, this only applies to vSphere specific parameters

**Comment by simu** [comment]
> I tested it and:
> 
> ```
>   openshift4_nodes:
>     nodeGroups:
>       master:
>         replicas: 3
>         state: 'Active'
> ```
> 
> does not change a thing, but thats probably due to incompetence on my side 🤦‍♂️

Looks like you're missing a `spec` in there if you compare it to the snippet I posted

**Pull request closed without merging**
